version: "3.8"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=MYDB
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  label_studio:
    container_name: label_studio
    restart: always
    image: heartexlabs/label-studio:latest
    ports:
      - "8080:8080"
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=<password>
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=<ip>
      - LABEL_STUDIO_ALLOW_ORGANIZATION_WEBHOOKS=true
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/home/user
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=<email_adress>
      - LABEL_STUDIO_PASSWORD=<password>
    volumes:
      - ./data/label_studio/files:/home/user
      - ./data/label_studio/data:/label-studio/data
    user: root:1001
    depends_on:
      - postgres